/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminAvisosRouteImport } from './routes/admin.avisos'
import { Route as AdminCarteirinhasRouteImport } from './routes/admin.carteirinhas'
import { Route as AdminDocumentosRouteImport } from './routes/admin.documentos'
import { Route as AdminEmbarcacoesRouteImport } from './routes/admin.embarcacoes'
import { Route as AdminMapaRouteImport } from './routes/admin.mapa'
import { Route as AdminPescadoresRouteImport } from './routes/admin.pescadores'
import { Route as AdminSaidasRouteImport } from './routes/admin.saidas'
import { Route as AdminSegurancaRouteImport } from './routes/admin.seguranca'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin.solicitacoes'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAvisosRouteImport } from './routes/app.avisos'
import { Route as AppCarteirinhaRouteImport } from './routes/app.carteirinha'
import { Route as AppEmbarcacoesRouteImport } from './routes/app.embarcacoes'
import { Route as AppHojeRouteImport } from './routes/app.hoje'
import { Route as AppMapaRouteImport } from './routes/app.mapa'
import { Route as AppMareRouteImport } from './routes/app.mare'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminAvisosIdRouteImport } from './routes/admin.avisos.$id'
import { Route as AdminAvisosNovoRouteImport } from './routes/admin.avisos.novo'
import { Route as AdminEmbarcacoesIdRouteImport } from './routes/admin.embarcacoes.$id'
import { Route as AdminPescadoresIdRouteImport } from './routes/admin.pescadores.$id'
import { Route as AdminSaidasIdRouteImport } from './routes/admin.saidas.$id'
import { Route as AppAvisosIdRouteImport } from './routes/app.avisos.$id'
import { Route as AppConfiguracoesNotificacoesRouteImport } from './routes/app.configuracoes.notificacoes'
import { Route as AppConfiguracoesPrivacidadeRouteImport } from './routes/app.configuracoes.privacidade'
import { Route as AppEmbarcacoesNovaRouteImport } from './routes/app.embarcacoes.nova'
import { Route as AppPerfilDadosRouteImport } from './routes/app.perfil.dados'
import { Route as AdminSaidasIdAcompanhamentoRouteImport } from './routes/admin.saidas.$id.acompanhamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvisosRoute = AdminAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarteirinhasRoute = AdminCarteirinhasRouteImport.update({
  id: '/carteirinhas',
  path: '/carteirinhas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmbarcacoesRoute = AdminEmbarcacoesRouteImport.update({
  id: '/embarcacoes',
  path: '/embarcacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapaRoute = AdminMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPescadoresRoute = AdminPescadoresRouteImport.update({
  id: '/pescadores',
  path: '/pescadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSaidasRoute = AdminSaidasRouteImport.update({
  id: '/saidas',
  path: '/saidas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSegurancaRoute = AdminSegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAvisosRoute = AppAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AppRoute,
} as any)
const AppCarteirinhaRoute = AppCarteirinhaRouteImport.update({
  id: '/carteirinha',
  path: '/carteirinha',
  getParentRoute: () => AppRoute,
} as any)
const AppEmbarcacoesRoute = AppEmbarcacoesRouteImport.update({
  id: '/embarcacoes',
  path: '/embarcacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppHojeRoute = AppHojeRouteImport.update({
  id: '/hoje',
  path: '/hoje',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppMareRoute = AppMareRouteImport.update({
  id: '/mare',
  path: '/mare',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAvisosIdRoute = AdminAvisosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAvisosRoute,
} as any)
const AdminAvisosNovoRoute = AdminAvisosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AdminAvisosRoute,
} as any)
const AdminEmbarcacoesIdRoute = AdminEmbarcacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEmbarcacoesRoute,
} as any)
const AdminPescadoresIdRoute = AdminPescadoresIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPescadoresRoute,
} as any)
const AdminSaidasIdRoute = AdminSaidasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSaidasRoute,
} as any)
const AppAvisosIdRoute = AppAvisosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAvisosRoute,
} as any)
const AppConfiguracoesNotificacoesRoute =
  AppConfiguracoesNotificacoesRouteImport.update({
    id: '/configuracoes/notificacoes',
    path: '/configuracoes/notificacoes',
    getParentRoute: () => AppRoute,
  } as any)
const AppConfiguracoesPrivacidadeRoute =
  AppConfiguracoesPrivacidadeRouteImport.update({
    id: '/configuracoes/privacidade',
    path: '/configuracoes/privacidade',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmbarcacoesNovaRoute = AppEmbarcacoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppEmbarcacoesRoute,
} as any)
const AppPerfilDadosRoute = AppPerfilDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => AppPerfilRoute,
} as any)
const AdminSaidasIdAcompanhamentoRoute =
  AdminSaidasIdAcompanhamentoRouteImport.update({
    id: '/acompanhamento',
    path: '/acompanhamento',
    getParentRoute: () => AdminSaidasIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/avisos': typeof AdminAvisosRouteWithChildren
  '/admin/carteirinhas': typeof AdminCarteirinhasRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/embarcacoes': typeof AdminEmbarcacoesRouteWithChildren
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/pescadores': typeof AdminPescadoresRouteWithChildren
  '/admin/saidas': typeof AdminSaidasRouteWithChildren
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/app/avisos': typeof AppAvisosRouteWithChildren
  '/app/carteirinha': typeof AppCarteirinhaRoute
  '/app/embarcacoes': typeof AppEmbarcacoesRouteWithChildren
  '/app/hoje': typeof AppHojeRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/mare': typeof AppMareRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/avisos/$id': typeof AdminAvisosIdRoute
  '/admin/avisos/novo': typeof AdminAvisosNovoRoute
  '/admin/embarcacoes/$id': typeof AdminEmbarcacoesIdRoute
  '/admin/pescadores/$id': typeof AdminPescadoresIdRoute
  '/admin/saidas/$id': typeof AdminSaidasIdRouteWithChildren
  '/app/avisos/$id': typeof AppAvisosIdRoute
  '/app/configuracoes/notificacoes': typeof AppConfiguracoesNotificacoesRoute
  '/app/configuracoes/privacidade': typeof AppConfiguracoesPrivacidadeRoute
  '/app/embarcacoes/nova': typeof AppEmbarcacoesNovaRoute
  '/app/perfil/dados': typeof AppPerfilDadosRoute
  '/admin/saidas/$id/acompanhamento': typeof AdminSaidasIdAcompanhamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/avisos': typeof AdminAvisosRouteWithChildren
  '/admin/carteirinhas': typeof AdminCarteirinhasRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/embarcacoes': typeof AdminEmbarcacoesRouteWithChildren
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/pescadores': typeof AdminPescadoresRouteWithChildren
  '/admin/saidas': typeof AdminSaidasRouteWithChildren
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/app/avisos': typeof AppAvisosRouteWithChildren
  '/app/carteirinha': typeof AppCarteirinhaRoute
  '/app/embarcacoes': typeof AppEmbarcacoesRouteWithChildren
  '/app/hoje': typeof AppHojeRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/mare': typeof AppMareRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/admin/avisos/$id': typeof AdminAvisosIdRoute
  '/admin/avisos/novo': typeof AdminAvisosNovoRoute
  '/admin/embarcacoes/$id': typeof AdminEmbarcacoesIdRoute
  '/admin/pescadores/$id': typeof AdminPescadoresIdRoute
  '/admin/saidas/$id': typeof AdminSaidasIdRouteWithChildren
  '/app/avisos/$id': typeof AppAvisosIdRoute
  '/app/configuracoes/notificacoes': typeof AppConfiguracoesNotificacoesRoute
  '/app/configuracoes/privacidade': typeof AppConfiguracoesPrivacidadeRoute
  '/app/embarcacoes/nova': typeof AppEmbarcacoesNovaRoute
  '/app/perfil/dados': typeof AppPerfilDadosRoute
  '/admin/saidas/$id/acompanhamento': typeof AdminSaidasIdAcompanhamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/avisos': typeof AdminAvisosRouteWithChildren
  '/admin/carteirinhas': typeof AdminCarteirinhasRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/embarcacoes': typeof AdminEmbarcacoesRouteWithChildren
  '/admin/mapa': typeof AdminMapaRoute
  '/admin/pescadores': typeof AdminPescadoresRouteWithChildren
  '/admin/saidas': typeof AdminSaidasRouteWithChildren
  '/admin/seguranca': typeof AdminSegurancaRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/app/avisos': typeof AppAvisosRouteWithChildren
  '/app/carteirinha': typeof AppCarteirinhaRoute
  '/app/embarcacoes': typeof AppEmbarcacoesRouteWithChildren
  '/app/hoje': typeof AppHojeRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/mare': typeof AppMareRoute
  '/app/perfil': typeof AppPerfilRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/admin/avisos/$id': typeof AdminAvisosIdRoute
  '/admin/avisos/novo': typeof AdminAvisosNovoRoute
  '/admin/embarcacoes/$id': typeof AdminEmbarcacoesIdRoute
  '/admin/pescadores/$id': typeof AdminPescadoresIdRoute
  '/admin/saidas/$id': typeof AdminSaidasIdRouteWithChildren
  '/app/avisos/$id': typeof AppAvisosIdRoute
  '/app/configuracoes/notificacoes': typeof AppConfiguracoesNotificacoesRoute
  '/app/configuracoes/privacidade': typeof AppConfiguracoesPrivacidadeRoute
  '/app/embarcacoes/nova': typeof AppEmbarcacoesNovaRoute
  '/app/perfil/dados': typeof AppPerfilDadosRoute
  '/admin/saidas/$id/acompanhamento': typeof AdminSaidasIdAcompanhamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/criar-conta'
    | '/entrar'
    | '/admin/auditoria'
    | '/admin/avisos'
    | '/admin/carteirinhas'
    | '/admin/documentos'
    | '/admin/embarcacoes'
    | '/admin/mapa'
    | '/admin/pescadores'
    | '/admin/saidas'
    | '/admin/seguranca'
    | '/admin/solicitacoes'
    | '/app/avisos'
    | '/app/carteirinha'
    | '/app/embarcacoes'
    | '/app/hoje'
    | '/app/mapa'
    | '/app/mare'
    | '/app/perfil'
    | '/auth/callback'
    | '/admin/'
    | '/app/'
    | '/admin/avisos/$id'
    | '/admin/avisos/novo'
    | '/admin/embarcacoes/$id'
    | '/admin/pescadores/$id'
    | '/admin/saidas/$id'
    | '/app/avisos/$id'
    | '/app/configuracoes/notificacoes'
    | '/app/configuracoes/privacidade'
    | '/app/embarcacoes/nova'
    | '/app/perfil/dados'
    | '/admin/saidas/$id/acompanhamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/criar-conta'
    | '/entrar'
    | '/admin/auditoria'
    | '/admin/avisos'
    | '/admin/carteirinhas'
    | '/admin/documentos'
    | '/admin/embarcacoes'
    | '/admin/mapa'
    | '/admin/pescadores'
    | '/admin/saidas'
    | '/admin/seguranca'
    | '/admin/solicitacoes'
    | '/app/avisos'
    | '/app/carteirinha'
    | '/app/embarcacoes'
    | '/app/hoje'
    | '/app/mapa'
    | '/app/mare'
    | '/app/perfil'
    | '/auth/callback'
    | '/admin'
    | '/app'
    | '/admin/avisos/$id'
    | '/admin/avisos/novo'
    | '/admin/embarcacoes/$id'
    | '/admin/pescadores/$id'
    | '/admin/saidas/$id'
    | '/app/avisos/$id'
    | '/app/configuracoes/notificacoes'
    | '/app/configuracoes/privacidade'
    | '/app/embarcacoes/nova'
    | '/app/perfil/dados'
    | '/admin/saidas/$id/acompanhamento'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/cadastro'
    | '/criar-conta'
    | '/entrar'
    | '/admin/auditoria'
    | '/admin/avisos'
    | '/admin/carteirinhas'
    | '/admin/documentos'
    | '/admin/embarcacoes'
    | '/admin/mapa'
    | '/admin/pescadores'
    | '/admin/saidas'
    | '/admin/seguranca'
    | '/admin/solicitacoes'
    | '/app/avisos'
    | '/app/carteirinha'
    | '/app/embarcacoes'
    | '/app/hoje'
    | '/app/mapa'
    | '/app/mare'
    | '/app/perfil'
    | '/auth/callback'
    | '/admin/'
    | '/app/'
    | '/admin/avisos/$id'
    | '/admin/avisos/novo'
    | '/admin/embarcacoes/$id'
    | '/admin/pescadores/$id'
    | '/admin/saidas/$id'
    | '/app/avisos/$id'
    | '/app/configuracoes/notificacoes'
    | '/app/configuracoes/privacidade'
    | '/app/embarcacoes/nova'
    | '/app/perfil/dados'
    | '/admin/saidas/$id/acompanhamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/avisos': {
      id: '/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AdminAvisosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carteirinhas': {
      id: '/admin/carteirinhas'
      path: '/carteirinhas'
      fullPath: '/admin/carteirinhas'
      preLoaderRoute: typeof AdminCarteirinhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/embarcacoes': {
      id: '/admin/embarcacoes'
      path: '/embarcacoes'
      fullPath: '/admin/embarcacoes'
      preLoaderRoute: typeof AdminEmbarcacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mapa': {
      id: '/admin/mapa'
      path: '/mapa'
      fullPath: '/admin/mapa'
      preLoaderRoute: typeof AdminMapaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pescadores': {
      id: '/admin/pescadores'
      path: '/pescadores'
      fullPath: '/admin/pescadores'
      preLoaderRoute: typeof AdminPescadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/saidas': {
      id: '/admin/saidas'
      path: '/saidas'
      fullPath: '/admin/saidas'
      preLoaderRoute: typeof AdminSaidasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seguranca': {
      id: '/admin/seguranca'
      path: '/seguranca'
      fullPath: '/admin/seguranca'
      preLoaderRoute: typeof AdminSegurancaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/avisos': {
      id: '/app/avisos'
      path: '/avisos'
      fullPath: '/app/avisos'
      preLoaderRoute: typeof AppAvisosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/carteirinha': {
      id: '/app/carteirinha'
      path: '/carteirinha'
      fullPath: '/app/carteirinha'
      preLoaderRoute: typeof AppCarteirinhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/embarcacoes': {
      id: '/app/embarcacoes'
      path: '/embarcacoes'
      fullPath: '/app/embarcacoes'
      preLoaderRoute: typeof AppEmbarcacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hoje': {
      id: '/app/hoje'
      path: '/hoje'
      fullPath: '/app/hoje'
      preLoaderRoute: typeof AppHojeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mare': {
      id: '/app/mare'
      path: '/mare'
      fullPath: '/app/mare'
      preLoaderRoute: typeof AppMareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/avisos/$id': {
      id: '/admin/avisos/$id'
      path: '/$id'
      fullPath: '/admin/avisos/$id'
      preLoaderRoute: typeof AdminAvisosIdRouteImport
      parentRoute: typeof AdminAvisosRoute
    }
    '/admin/avisos/novo': {
      id: '/admin/avisos/novo'
      path: '/novo'
      fullPath: '/admin/avisos/novo'
      preLoaderRoute: typeof AdminAvisosNovoRouteImport
      parentRoute: typeof AdminAvisosRoute
    }
    '/admin/embarcacoes/$id': {
      id: '/admin/embarcacoes/$id'
      path: '/$id'
      fullPath: '/admin/embarcacoes/$id'
      preLoaderRoute: typeof AdminEmbarcacoesIdRouteImport
      parentRoute: typeof AdminEmbarcacoesRoute
    }
    '/admin/pescadores/$id': {
      id: '/admin/pescadores/$id'
      path: '/$id'
      fullPath: '/admin/pescadores/$id'
      preLoaderRoute: typeof AdminPescadoresIdRouteImport
      parentRoute: typeof AdminPescadoresRoute
    }
    '/admin/saidas/$id': {
      id: '/admin/saidas/$id'
      path: '/$id'
      fullPath: '/admin/saidas/$id'
      preLoaderRoute: typeof AdminSaidasIdRouteImport
      parentRoute: typeof AdminSaidasRoute
    }
    '/app/avisos/$id': {
      id: '/app/avisos/$id'
      path: '/$id'
      fullPath: '/app/avisos/$id'
      preLoaderRoute: typeof AppAvisosIdRouteImport
      parentRoute: typeof AppAvisosRoute
    }
    '/app/configuracoes/notificacoes': {
      id: '/app/configuracoes/notificacoes'
      path: '/configuracoes/notificacoes'
      fullPath: '/app/configuracoes/notificacoes'
      preLoaderRoute: typeof AppConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes/privacidade': {
      id: '/app/configuracoes/privacidade'
      path: '/configuracoes/privacidade'
      fullPath: '/app/configuracoes/privacidade'
      preLoaderRoute: typeof AppConfiguracoesPrivacidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/embarcacoes/nova': {
      id: '/app/embarcacoes/nova'
      path: '/nova'
      fullPath: '/app/embarcacoes/nova'
      preLoaderRoute: typeof AppEmbarcacoesNovaRouteImport
      parentRoute: typeof AppEmbarcacoesRoute
    }
    '/app/perfil/dados': {
      id: '/app/perfil/dados'
      path: '/dados'
      fullPath: '/app/perfil/dados'
      preLoaderRoute: typeof AppPerfilDadosRouteImport
      parentRoute: typeof AppPerfilRoute
    }
    '/admin/saidas/$id/acompanhamento': {
      id: '/admin/saidas/$id/acompanhamento'
      path: '/acompanhamento'
      fullPath: '/admin/saidas/$id/acompanhamento'
      preLoaderRoute: typeof AdminSaidasIdAcompanhamentoRouteImport
      parentRoute: typeof AdminSaidasIdRoute
    }
  }
}

interface AdminAvisosRouteChildren {
  AdminAvisosIdRoute: typeof AdminAvisosIdRoute
  AdminAvisosNovoRoute: typeof AdminAvisosNovoRoute
}

const AdminAvisosRouteChildren: AdminAvisosRouteChildren = {
  AdminAvisosIdRoute: AdminAvisosIdRoute,
  AdminAvisosNovoRoute: AdminAvisosNovoRoute,
}

const AdminAvisosRouteWithChildren = AdminAvisosRoute._addFileChildren(
  AdminAvisosRouteChildren,
)

interface AdminEmbarcacoesRouteChildren {
  AdminEmbarcacoesIdRoute: typeof AdminEmbarcacoesIdRoute
}

const AdminEmbarcacoesRouteChildren: AdminEmbarcacoesRouteChildren = {
  AdminEmbarcacoesIdRoute: AdminEmbarcacoesIdRoute,
}

const AdminEmbarcacoesRouteWithChildren =
  AdminEmbarcacoesRoute._addFileChildren(AdminEmbarcacoesRouteChildren)

interface AdminPescadoresRouteChildren {
  AdminPescadoresIdRoute: typeof AdminPescadoresIdRoute
}

const AdminPescadoresRouteChildren: AdminPescadoresRouteChildren = {
  AdminPescadoresIdRoute: AdminPescadoresIdRoute,
}

const AdminPescadoresRouteWithChildren = AdminPescadoresRoute._addFileChildren(
  AdminPescadoresRouteChildren,
)

interface AdminSaidasIdRouteChildren {
  AdminSaidasIdAcompanhamentoRoute: typeof AdminSaidasIdAcompanhamentoRoute
}

const AdminSaidasIdRouteChildren: AdminSaidasIdRouteChildren = {
  AdminSaidasIdAcompanhamentoRoute: AdminSaidasIdAcompanhamentoRoute,
}

const AdminSaidasIdRouteWithChildren = AdminSaidasIdRoute._addFileChildren(
  AdminSaidasIdRouteChildren,
)

interface AdminSaidasRouteChildren {
  AdminSaidasIdRoute: typeof AdminSaidasIdRouteWithChildren
}

const AdminSaidasRouteChildren: AdminSaidasRouteChildren = {
  AdminSaidasIdRoute: AdminSaidasIdRouteWithChildren,
}

const AdminSaidasRouteWithChildren = AdminSaidasRoute._addFileChildren(
  AdminSaidasRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminAvisosRoute: typeof AdminAvisosRouteWithChildren
  AdminCarteirinhasRoute: typeof AdminCarteirinhasRoute
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminEmbarcacoesRoute: typeof AdminEmbarcacoesRouteWithChildren
  AdminMapaRoute: typeof AdminMapaRoute
  AdminPescadoresRoute: typeof AdminPescadoresRouteWithChildren
  AdminSaidasRoute: typeof AdminSaidasRouteWithChildren
  AdminSegurancaRoute: typeof AdminSegurancaRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminAvisosRoute: AdminAvisosRouteWithChildren,
  AdminCarteirinhasRoute: AdminCarteirinhasRoute,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminEmbarcacoesRoute: AdminEmbarcacoesRouteWithChildren,
  AdminMapaRoute: AdminMapaRoute,
  AdminPescadoresRoute: AdminPescadoresRouteWithChildren,
  AdminSaidasRoute: AdminSaidasRouteWithChildren,
  AdminSegurancaRoute: AdminSegurancaRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppAvisosRouteChildren {
  AppAvisosIdRoute: typeof AppAvisosIdRoute
}

const AppAvisosRouteChildren: AppAvisosRouteChildren = {
  AppAvisosIdRoute: AppAvisosIdRoute,
}

const AppAvisosRouteWithChildren = AppAvisosRoute._addFileChildren(
  AppAvisosRouteChildren,
)

interface AppEmbarcacoesRouteChildren {
  AppEmbarcacoesNovaRoute: typeof AppEmbarcacoesNovaRoute
}

const AppEmbarcacoesRouteChildren: AppEmbarcacoesRouteChildren = {
  AppEmbarcacoesNovaRoute: AppEmbarcacoesNovaRoute,
}

const AppEmbarcacoesRouteWithChildren = AppEmbarcacoesRoute._addFileChildren(
  AppEmbarcacoesRouteChildren,
)

interface AppPerfilRouteChildren {
  AppPerfilDadosRoute: typeof AppPerfilDadosRoute
}

const AppPerfilRouteChildren: AppPerfilRouteChildren = {
  AppPerfilDadosRoute: AppPerfilDadosRoute,
}

const AppPerfilRouteWithChildren = AppPerfilRoute._addFileChildren(
  AppPerfilRouteChildren,
)

interface AppRouteChildren {
  AppAvisosRoute: typeof AppAvisosRouteWithChildren
  AppCarteirinhaRoute: typeof AppCarteirinhaRoute
  AppEmbarcacoesRoute: typeof AppEmbarcacoesRouteWithChildren
  AppHojeRoute: typeof AppHojeRoute
  AppMapaRoute: typeof AppMapaRoute
  AppMareRoute: typeof AppMareRoute
  AppPerfilRoute: typeof AppPerfilRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppConfiguracoesNotificacoesRoute: typeof AppConfiguracoesNotificacoesRoute
  AppConfiguracoesPrivacidadeRoute: typeof AppConfiguracoesPrivacidadeRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAvisosRoute: AppAvisosRouteWithChildren,
  AppCarteirinhaRoute: AppCarteirinhaRoute,
  AppEmbarcacoesRoute: AppEmbarcacoesRouteWithChildren,
  AppHojeRoute: AppHojeRoute,
  AppMapaRoute: AppMapaRoute,
  AppMareRoute: AppMareRoute,
  AppPerfilRoute: AppPerfilRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppConfiguracoesNotificacoesRoute: AppConfiguracoesNotificacoesRoute,
  AppConfiguracoesPrivacidadeRoute: AppConfiguracoesPrivacidadeRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
